### ISSUE TITLE
cannot import name 'external_account_authorized_user' from 'google.auth'

### ISSUE THREAD

**Issue by dholbach** [fluxcd/stats#16]
From https://github.com/fluxcd/stats/actions/runs/3317441468/jobs/5482779200

```py
Traceback (most recent call last):
  File "/importer.py", line 5, in <module>
    import gspread
  File "/usr/local/lib/python3.8/dist-packages/gspread/__init__.py", line 16, in <module>
    from .auth import oauth, service_account, service_account_from_dict
  File "/usr/local/lib/python3.8/dist-packages/gspread/auth.py", line 16, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "/usr/local/lib/python3.8/dist-packages/google_auth_oauthlib/__init__.py", line 21, in <module>
    from .interactive import get_user_credentials
  File "/usr/local/lib/python3.8/dist-packages/google_auth_oauthlib/interactive.py", line 27, in <module>
    import google_auth_oauthlib.flow
  File "/usr/local/lib/python3.8/dist-packages/google_auth_oauthlib/flow.py", line 69, in <module>
    import google_auth_oauthlib.helpers
  File "/usr/local/lib/python3.8/dist-packages/google_auth_oauthlib/helpers.py", line 27, in <module>
    from google.auth import external_account_authorized_user
ImportError: cannot import name 'external_account_authorized_user' from 'google.auth' (/usr/local/lib/python3.8/dist-packages/google/auth/__init__.py)
```

cc @kingdonb

**Comment by kingdonb** [comment]
Ah yeas, I am the maintainer now (`meme_look_at_me.jpg`)

It will take me a little bit to get familiar with that code and what it's doing, actually looks like it might be a quick fix: https://stackoverflow.com/a/74193071/661659
